### ISSUE TITLE
Could u please change the default slave name? 

### ISSUE THREAD

**Issue by alexya** [eea/eea.docker.jenkins.slave#3]
![image](https://user-images.githubusercontent.com/2831220/32157113-624bde22-bd0f-11e7-894f-4ce642dbda5b.png)

In file `docker-entrypoint.sh`, you generate the slave name with the format `$JENKINS_NAME@$IP`.  But when I hooked one slave into Jenkins master, it told me that the name was unsafe. 

Does it make sense to use another character to show `@` meaning?

**Comment by valentinab25** [comment]
Solved in 3.6.1
